wandb_version: 1

base_model_type:
  desc: null
  value: gpt2
total_batch_size:
  desc: null
  value: 524288
B:
  desc: null
  value: 16
T:
  desc: null
  value: 1024
grad_accum_steps:
  desc: null
  value: 4
max_lr:
  desc: null
  value: 0.0006
min_lr:
  desc: null
  value: 5.9999999999999995e-05
warmup_steps:
  desc: null
  value: 715
max_steps:
  desc: null
  value: 19073
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1732886274
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
